### DISCUSSION TITLE
Table from TOML file

### DISCUSSION THREAD

**Discussion by attakei** [atsphinx/atsphinx.github.io#7] [Ideas]
## Example

Input:

```toml
[[deps]]
name = "yourname"
version = "v0.1.0"
```

```rst
.. toml-table:: ./source.toml
   :item: deps

   name
   version
```

Output:

(emulate this)

```rst
.. csv-table::
   :header: "name", "version"

   "yourname", "v0.1.0"
```
